chriskempson/base16-schemes-source

- list.yaml
Like it says in the title. Also best of luck with the new setup!
> added atelier-schemes link to repo

- list.yaml
This is a vibrant, bright scheme that includes dark and light variants.
> Add Unikitty scheme

- list.yaml
[Rebecca](https://github.com/vic/base16-rebecca-scheme) is a purple dark scheme based on the origin [emacs theme](https://github.com/vic/rebecca-theme)
> Add rebecca scheme

- list.yaml
to: @chriskempson 
cc: @ewang12
> Add the Circus theme

- list.yaml
Contains four themes based on https://github.com/equinusocio/material-theme
> Add base16-materialtheme-scheme

- list.yaml
the base16-dracula repository was moved to the dracula project.
> moved dracula repository

- list.yaml
The corresponding pull request to [the main base16 repo](https://github.com/chriskempson/base16) can be found [here](https://github.com/chriskempson/base16/pull/147).
> Update list.yaml to reflect new solarized location

- list.yaml
It has already been added  in chriskempson/base16 , but I forgot to add it here so …
> Add iA scheme

- list.yaml
A refreshing treat in the summer heat!
> Added source for the Fruit Soda scheme

- list.yaml
Hello! I am working on implementing papercolor for base16. This is the first step in doing so; so please let me know if I am missing anything.
Cheers!
> Add Papercolor to list.yaml

- list.yaml
Added a scheme to the sources list.
> Adding purpledream

- list.yaml
Adds [`atlas`](https://github.com/ajlende/base16-atlas-scheme) scheme to the list
> Add atlas scheme

- list.yaml
This supersedes #44, #45, #46, #47, and #48 as it includes those changes merged together. This is similar to the main base16 repo PR from this fork.
> Sync changes with fork

- list.yaml
iTerm2 Espresso theme, ported to Base16 format with a few minor changes.
> Add espresso theme

- list.yaml
[base16-hardcore-scheme](https://github.com/callerc1/base16-hardcore-scheme) 🌈
> Add base16-hardcore-scheme

- list.yaml
Light and dark color schemes with bright colors.
> add Humanoid color schemes

- list.yaml
https://github.com/tartansandal/base16-dirtysea-scheme
> Add dirtysea scheme

- list.yaml
> add vulcan scheme

- list.yaml
> Added darkmoss scheme

- list.yaml
per request and while I was still thinking about it, threw that bad boy on there. 
Thanks again, 
TLH
> added vice scheme to the list

- list.yaml
Here's my latest scheme, has a light and dark version.
https://github.com/Misterio77/base16-silk-scheme
> Add silk scheme

- list.yaml
Hi there,
I'm just adding a base16 color scheme "Kimber" which I'm going to be maintaining.
Thank you for the great work on this project! Hope you are all well and safe during this period.
> Adding base16-kimber-scheme

- list.yaml
based on tender.vim https://github.com/jacoborus/tender.vim
> add tender color scheme

- list.yaml
Added color scheme danqing -- a color scheme based on colors used in Chinese paintings.
> Added colors cheme danqing

- list.yaml
base16 qualitative HCL color palette
https://www.reddit.com/r/unixporn/comments/hjzw5f/oc_qualitative_color_palette_for_ansi_terminal
> Add qualia to list.yaml

- list.yaml
[base16-shades-of-purple](https://github.com/ahmadawais/base16-shades-of-purple) 🦄
> Add Shades of Purple scheme

- list.yaml
Color palette with a nice pink. https://github.com/b3nj5m1n/base16-pinky-scheme
> Add pinky scheme

- list.yaml
Here's a light pink theme
https://github.com/Misterio77/base16-sakura-scheme
> Add Sakura scheme
